"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Main from "./components/main";
import Header from "./components/Header";
import AppLogin from "./login/page";
import AppTodo from "./todo/page";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import reportWebVitals from "@/reportWebVitals";
import "./components/LoginTest/index.css";

const inter = Inter({ subsets: ["latin"] });

const queryClient = new QueryClient();

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ margin: 0 }}>
        <QueryClientProvider client={queryClient}>
          <Header />
          <Main>{children}</Main>
        </QueryClientProvider>
      </body>
    </html>
  );
}

reportWebVitals();
